### ISSUE TITLE
java.lang.RuntimeException: java.io.IOException: Stream closed

### ISSUE THREAD

**Issue by rofleksey** [Osiris-Team/HBrowser#13]
Error during start of NodeJS! Details:

java.lang.RuntimeException: java.io.IOException: Stream closed
java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: Stream closed
	at com.osiris.headlessbrowser.js.contexts.NodeContext.<init>(NodeContext.java:164)
	at com.osiris.headlessbrowser.windows.PlaywrightWindow.<init>(PlaywrightWindow.java:56)
	at com.osiris.headlessbrowser.windows.WindowBuilder.buildPlaywrightWindow(WindowBuilder.java:81)
Caused by: java.lang.RuntimeException: java.io.IOException: Stream closed
	at com.osiris.headlessbrowser.js.contexts.NodeContext.executeJavaScript(NodeContext.java:436)
	at com.osiris.headlessbrowser.js.contexts.NodeContext.executeJavaScript(NodeContext.java:342)
	at com.osiris.headlessbrowser.js.contexts.NodeContext.<init>(NodeContext.java:149)
	... 87 more
Caused by: java.io.IOException: Stream closed
	at java.base/java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:442)
	at java.base/java.io.OutputStream.write(OutputStream.java:157)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at com.osiris.headlessbrowser.js.contexts.NodeContext.writeLine(NodeContext.java:327)
	at com.osiris.headlessbrowser.js.contexts.NodeContext.executeJavaScriptFromFile(NodeContext.java:512)
	at com.osiris.headlessbrowser.js.contexts.NodeContext.executeJavaScript(NodeContext.java:401)
	... 89 more

**Comment by Osiris-Team** [comment]
Looks like something went wrong with the nodejs process, can you share the code that led to this error?

**Comment by Osiris-Team** [comment]
Closing because of no response
