### ISSUE TITLE
Wrong NodeJS architecture in installation (Windows x64/amd64)

### ISSUE THREAD

**Issue by nocelab** [Osiris-Team/HBrowser#15]
Running a test code in a Windows x64/amd64 pc, HBrowser install NodeJS from node-v20.7.0-win-**arm**64.zip and then when the task starts, fails with:

```
Exception in thread "main" java.lang.RuntimeException: java.io.IOException:
Cannot run program "C:\temp\Cgil\HBrowser\headless-browser\node-js\node-js-installation\node-v20.7.0-win-arm64\node.exe
```

**Comment by Osiris-Team** [comment]
@nocelab Ok guess there is an issue here: https://github.com/Osiris-Team/HBrowser/blob/9615a327cc6535be003f31faf189d879dcfb6894/src/main/java/com/osiris/headlessbrowser/js/contexts/NodeContext.java#L258
Can you please enable the debug output (I think you can set it in the browser builder) and post the log?

**Comment by nocelab** [comment]
```
Error during start of NodeJS! Details:
Exception in thread "main" java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\temp\HBrowser\headless-browser\node-js\node-js-installation\node-v20.8.0-win-arm64\node.exe" (in directory "C:\temp\HBrowser\headless-browser\node-js\node-js-working-dir"): CreateProcess error=216, La versione di %1 è incompatibile con la versione di Windows in esecuzione. Verificare le informazioni di sistema e contattare il distributore del software
	at com.osiris.headlessbrowser.js.contexts.NodeContext.<init>(NodeContext.java:227)
	at com.osiris.headlessbrowser.windows.PlaywrightWindow.<init>(PlaywrightWindow.java:57)
	at com.osiris.headlessbrowser.windows.WindowBuilder.buildPlaywrightWindow(WindowBuilder.java:75)
	at com.osiris.headlessbrowser.ZucchettiTest.main(ZucchettiTest.java:67)
Caused by: java.io.IOException: Cannot run program "C:\temp\HBrowser\headless-browser\node-js\node-js-installation\node-v20.8.0-win-arm64\node.exe" (in directory "C:\temp\HBrowser\headless-browser\node-js\node-js-working-dir"): CreateProcess error=216, La versione di %1 è incompatibile con la versione di Windows in esecuzione. Verificare le informazioni di sistema e contattare il distributore del software
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.osiris.headlessbrowser.js.contexts.NodeContext.<init>(NodeContext.java:187)
	... 3 more
Caused by: java.io.IOException: CreateProcess error=216, La versione di %1 è incompatibile con la versione di Windows in esecuzione. Verificare le informazioni di sistema e contattare il distributore del software
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 4 more

Process finished with exit code 1
```

**Comment by Osiris-Team** [comment]
@nocelab are you using the latest version of HBrowser? Because I cant reproduce this ( my system is also windows/amd64)

**Comment by nocelab** [comment]
You are right... I not with latest version, this is a duplication of [#14](https://github.com/Osiris-Team/HBrowser/issues/14) issue... sorry!

**Comment by Osiris-Team** [comment]
Np, good that its fixed then ^^
