### ISSUE TITLE
Growing node.exe memory

### ISSUE THREAD

**Issue by nocelab** [Osiris-Team/HBrowser#9]
Hi, in Windows machine I'm testing a loop with 2 `load` method with Playwright browser and I note that the process `node.exe` still grow without ever release.
Is it correct? Is there some trick to release it?

**Comment by Osiris-Team** [comment]
@nocelab can you share the code? I didnt notice anything like that when testing.

**Comment by nocelab** [comment]
this is sample code (Windows 10 with OpenJDK 8u222-b10):

```js
HBrowser hBrowser = new HBrowser();
PlaywrightWindow hb = hBrowser.openCustomWindow().headless(false).buildPlaywrightWindow();

for (int i = 0; i < 100; i++) {
    hb.load("www.google.it");
    hb.fill("[aria-label=\"Cerca\"]", "searching something");
    hb.holdKey("Tab");
    // click and wait...
    hb.getJsContext().executeJavaScript(""+
            "await Promise.all([\n"+
            " page.click(':nth-match(:text(\"Cerca con Google\"), 2)'),\n"+
            " page.waitForNavigation()\n"+
            "]);");
    System.out.println(hb.getOuterHtml().text());
}
hb.close();
```

and this is memory graph:

![image](https://user-images.githubusercontent.com/9341832/153609654-5d8e1527-9a0a-4584-b844-65299639a650.png)

**Comment by Osiris-Team** [comment]
Ok I tested this code first just to make sure node was working fine by default:
```java
HBrowser hBrowser = new HBrowser();
        try(PlaywrightWindow window = hBrowser.openWindow()){
            window.load("www.google.com");
            System.out.println("Loaded page! Exit the program once finished with ram analysis...");
            while (true)
                Thread.sleep(1000);
        } catch (NodeJsCodeException | InterruptedException e) {
            e.printStackTrace();
        }
```
![image](https://user-images.githubusercontent.com/59899645/153615621-f6974cc5-008e-44df-a29c-43bcc161da6c.png)
And it looks good since the node.exe uses only a steady amount of 31mb.

Then I tested your code (slightly modified):
```java
HBrowser hBrowser = new HBrowser();
        try(PlaywrightWindow window = hBrowser.openCustomWindow().headless(false).buildPlaywrightWindow()){
            for (int i = 0; i < 100; i++) {
                window.load("www.google.it");
                window.fill("[aria-label=\"Cerca\"]", "searching something");
                window.holdKey("Tab");
                // click and wait...
                window.getJsContext().executeJavaScript(""+
                        "await Promise.all([\n"+
                        " page.click(':nth-match(:text(\"Cerca con Google\"), 2)'),\n"+
                        " page.waitForNavigation()\n"+
                        "]);");
                System.out.println("Run: "+i);
            }
        } catch (NodeJsCodeException e) {
            e.printStackTrace();
        }
```
Your code throws following exception:
```
com.osiris.headlessbrowser.exceptions.NodeJsCodeException: Error during JavaScript code execution! Details: 
CAUGHT JS-EXCEPTION: TimeoutError
MESSAGE: page.fill: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "[aria-label="Cerca"]"
============================================================
LINE: undefined
STACK: page.fill: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "[aria-label="Cerca"]"
============================================================
    at REPL12:2:12
    at REPL12:8:4


	at com.osiris.headlessbrowser.js.contexts.NodeContext.executeJavaScript(NodeContext.java:383)
	at com.osiris.headlessbrowser.js.contexts.NodeContext.executeJavaScript(NodeContext.java:304)
	at com.osiris.headlessbrowser.windows.PlaywrightWindow.fill(PlaywrightWindow.java:711)
	at com.osiris.headlessbrowser.windows.PlaywrightWindow.fill(PlaywrightWindow.java:681)
	at com.osiris.headlessbrowser.issues.Issue9.main(Issue9.java:13)

Process finished with exit code 0

```
Thus I wasn't able to see the same increase in memory as you since it aborts. Maybe the missing try/catch was somehow your issue?

**Comment by nocelab** [comment]
You have to adapt my code with your google.com right localized labels... this graph with your try/catch code:

![image](https://user-images.githubusercontent.com/9341832/153622453-ee69fc4e-1daa-4a27-94e4-be32c45e0532.png)

**Comment by nocelab** [comment]
Ok... I'am happy!
You are right, perhaps something like https://github.com/microsoft/playwright/issues/6319.
I will deppen with Playwright... thanks!
